spring:
  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    timeout: ${redis.timeout}
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
