spring:
  datasource:
    driver-class-name:  ${datasource.driver-class-name}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
mybatis:
  configuration:
    map-underscore-to-camel-case: true